//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave_2._0.Properties.Lang {
    using System;
    
    
     
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
     
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang___Copier {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang___Copier() {
        }
        
         
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
         
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave_2._0.Properties.Lang.Lang - Copier", typeof(Lang___Copier).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
         
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
         
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Cancel.
         
        internal static string CancelSave {
            get {
                return ResourceManager.GetString("CancelSave", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Complete Save.
         
        internal static string CompleteType {
            get {
                return ResourceManager.GetString("CompleteType", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Create.
         
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Save in progress :.
         
        internal static string CurrentSave {
            get {
                return ResourceManager.GetString("CurrentSave", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Delete.
         
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Destination Path.
         
        internal static string DestinationPath {
            get {
                return ResourceManager.GetString("DestinationPath", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Differential Save.
         
        internal static string DifferencialType {
            get {
                return ResourceManager.GetString("DifferencialType", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Done !.
         
        internal static string DoneStatus {
            get {
                return ResourceManager.GetString("DoneStatus", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Encryption.
         
        internal static string Encryption {
            get {
                return ResourceManager.GetString("Encryption", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à English.
         
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Fran&amp;#231;ais.
         
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Global Settings.
         
        internal static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à ID.
         
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Launch.
         
        internal static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Launch All.
         
        internal static string LaunchAll {
            get {
                return ResourceManager.GetString("LaunchAll", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à EasySave 3.0.
         
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Maximum file size for simultaneous transfert :.
         
        internal static string MaximumFileSize {
            get {
                return ResourceManager.GetString("MaximumFileSize", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Maximum Size :.
         
        internal static string MaximumFileSizeValue {
            get {
                return ResourceManager.GetString("MaximumFileSizeValue", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Modify.
         
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Name.
         
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Pause.
         
        internal static string PauseSave {
            get {
                return ResourceManager.GetString("PauseSave", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Extension Priority.
         
        internal static string PriorityFileExtension {
            get {
                return ResourceManager.GetString("PriorityFileExtension", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Resume.
         
        internal static string ResumeSave {
            get {
                return ResourceManager.GetString("ResumeSave", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Running....
         
        internal static string RunningStatus {
            get {
                return ResourceManager.GetString("RunningStatus", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Progress :.
         
        internal static string ProgressionSave {
            get {
                return ResourceManager.GetString("ProgressionSave", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Save State.
         
        internal static string SaveStateStatus {
            get {
                return ResourceManager.GetString("SaveStateStatus", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Status :.
         
        internal static string SaveStatus {
            get {
                return ResourceManager.GetString("SaveStatus", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Save Type.
         
        internal static string SaveType {
            get {
                return ResourceManager.GetString("SaveType", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Settings.
         
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
         
        ///   Recherche une chaîne localisée semblable à Source Path.
         
        internal static string SourcePath {
            get {
                return ResourceManager.GetString("SourcePath", resourceCulture);
            }
        }
    }
}
